[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'forge-cache'
allow_paths = ["../node_modules"]
solc = '0.8.19'
optimizer = true
optimizer_runs = 999_999
fs_permissions = [{ access = "read", path = "./"}]

[profile.ci]
verbosity = 4

[rpc_endpoints]
mainnet = "https://eth.merkle.io"
optimism = "https://mainnet.optimism.io	"
