cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-starknet"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
byteorder.workspace = true
cainome.workspace = true
starknet.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url.workspace = true

hyperlane-core = { path = "../../hyperlane-core", features = [
    "async",
    "starknet",
] }

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["starknet"] }
